### ISSUE TITLE
Bollinger band issue - half deviations not implemented

### ISSUE THREAD

**Issue by efiedoro** [Nedomas/indicators#1]
I do not believe that half deviations are implemented in this gem. Deviation 2 and 2.5 are the same as 3 and 3.5.  Most online websites let you run half numbers.

Here is a code snippet I was running:

my_data = Indicators::Data.new(Securities::Stock.new(:symbol => 'KO', :start_date => '2012-09-24', :end_date => '2013-01-01').output)

my_data.calc(:type => :bb, :params => [15, 2])
my_data.calc(:type => :bb, :params => [15, 2.5])
my_data.calc(:type => :bb, :params => [15, 3])
my_data.calc(:type => :bb, :params => [15, 3.5])

35.8408728579227  -  BB 2.0
35.8408728579227  -  BB2.5
35.23830928688404 - BB 3.0
35.23830928688404   - BB 3.5

**Comment by Nedomas** [comment]
Thanks for noticing about this random bug! I'm going to push this to rubygems with the next minor release, but if you want to use it now, you can just use it straight from Github. 

``` ruby
gem 'indicators', :git => 'git://github.com/Nedomas/indicators.git'
```

[37.04600000000001, 38.251127142077316, 35.8408728579227] - BB 2
[37.04600000000001, 38.49215257049278, 35.599847429507236] - BB 2.4

**Comment by efiedoro** [comment]
No problem. I really like the simplicity of this gem. I will look to help you with it in the future. Maybe something like Caulkin's money flow (CMF) or volume vs. volume MA
